credentials:
  usernames:
    bobbert:
      name: psvtechbobby@gmail.com
      password: "$2b$12$aKMKyWMvl078z1aYoV4OS.q/xNQ2nkTRdPt9JIItaTEoHgQaBTOXq"
      role: user
    sirisha:
        name: Sirisha
        password: "$2b$12$pmCfBgeb5mMGZE99CgOmjOFI41FOdsyYbnlizVextpWLhb5nTiKwK"
        role: user
    bobby:
      name: Bobby
      password: "$2b$12$P1P0Rh2E/HsN4TJbo1r9M.eVCP6ExZk.9PwApHMKGXrOqLUM2xDJm"
      role: user
    varun:
      name: Varun
      password: "$2b$12$8cSjlMRsxSC9MC9s.PqBVOlIFKq3Lb5YwrlT1j3j525IL5ZyD.x2O"
      role: admin

cookie:
  expiry_days: 30
  key: "random_signature_key"
  name: "auth_cookie"
